services:

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./etc/nginx.conf:/etc/nginx/nginx.conf
      - ./www:/srv
    ports:
      - "80:80"

#  caddy:
#    image: caddy:latest
#    environment:
#      - SITE=localhost:80
#    volumes:
#      - ./etc/Caddyfile:/etc/caddy/Caddyfile
#      - ./www:/srv
#    ports:
#      - "80:80"
#      - "443:443"

  php:
    container_name: php_fpm
    image: php:8.3-fpm
    user: "root:root"
    volumes:
      - ./www:/srv
      - ./etc/php-fpm.conf:/usr/local/etc/php-fpm.d/zzz-custom.conf
    expose:
      - 9000