version: "3.9"
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./html:/html
    ports:
      - "8055:80"
  php:
    container_name: php
    image: php:8.0-fpm
    volumes:
      - ./html:/html