services:

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./etc/nginx.conf:/etc/nginx/nginx.conf
      - ./www:/var/www/html
    ports:
      - "80:80"

  #  caddy:
  #    image: caddy:latest
  #    environment:
  #      - SITE=localhost:80
  #    volumes:
  #      - ./etc/Caddyfile:/etc/caddy/Caddyfile
  #      - ./www:/srv
  #    ports:
  #      - "80:80"
  #      - "443:443"

  php:
    container_name: php_fpm
    build:
      context: .
    volumes:
      - ./www:/srv
      - ./etc/php-fpm.conf:/usr/local/etc/php-fpm.d/zzz-custom.conf
      - ./etc/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
    expose:
      - 9000
    ports:
      - "127.0.0.1:9000:9000"
