version: "3.9"
services:

  caddy:
    image: caddy:latest
    environment:
      - SITE=localhost:80
    volumes:
      - ./etc/Caddyfile:/etc/caddy/Caddyfile
      - ./www:/srv
    ports:
      - "80:80"
      - "443:443"

  php:
    container_name: php_fpm
    image: php:8.1-fpm
    user: "root:root"
    volumes:
      - ./www:/srv
    expose:
      - 9000